### PR TITLE
UI create thread

### PR DESCRIPTION
**Pull request by SunnyRo**
Resolves cptchuckles/SharpScape#46

Lemme know if I need to change anything. This task is to create a UI for creating a thread to Topic index.

### CODE REVIEW

**Comment by cptchuckles** [comment]
I'm just realizing how convoluted our naming scheme has become.  We now have Posts, Comments, Topics, and Threads, but what's the difference between Posts and Comments, and what's the difference between Topics and Categories or Threads? Maybe some things just need to be renamed, but right now I can't tell what things are anymore.

We need to stick to this diagram (this is also on the main readme for the repo).

**Comment by SunnyRo** [comment]
Thats why i asked you few days ago to rename the files and folders the way you like. Based on the diagram, Topic = Thread, Comment = Post, Categories = List of Threads. its up to you If u want me to rename the file in the folders lemme know but I might cause conflict later since people are using the comment and topic now (just change names).

**Comment by cptchuckles** [comment]
Ok do you think it would be easier to rename things on your end, or should I just merge this and then rename everything?

Also Comment = Post but we have both now, so one needs to get deleted?

**Comment by SunnyRo** [comment]
I think you should merge this. Then I will make another pull request for that. Im also trying to figure out but have some ideas what files I have to change.

**Pull request merged**
